threshold: 60
checks:
  topics:
    topicCorrections:
      pan-os:
      - panos
      globalprotect:
      - global-protect
      logging-service:
      - loggingservice
      cortex-data-lake:
      - cdl
      autofocus:
      - auto-focus
      vm-series:
      - vmseries
      cloud-services:
      - cloudservices
    requiredTopic:
      - autofocus
      - cloud-services
      - cortex
      - cortex-data-lake
      - cortex-xdr
      - cortex-xdr-analytics
      - cortex-xdr-investigation-and-response
      - demisto
      - directory-sync-service
      - evident
      - globalprotect
      - hardware
      - hub
      - log-forwarding-app
      - logging-service
      - pan-os
      - panorama
      - prisma-access
      - prisma-cloud
      - prisma-cloud-compute-edition
      - prisma-saas
      - secdo
      - security-lifecycle-review-slr
      - traps
      - traps-management-service
      - vm-series
      - wildfire
